"""add user_id foreign key to markers table

Revision ID: a6437d861765
Revises: 11356a58f2a1
Create Date: 2025-06-15 15:56:04.707042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6437d861765'
down_revision: Union[str, None] = '11356a58f2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'markers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'markers', type_='foreignkey')
    op.drop_column('markers', 'user_id')
    # ### end Alembic commands ###
